Use getopt for option handling

diff --git a/ec2-metadata b/ec2-metadata
--- a/ec2-metadata
+++ b/ec2-metadata
@@ -158,59 +158,73 @@ if [ "$#" -eq 0 ]; then
 	print_all
 fi
 
+declare -a actions
+shortopts=almnbithokzPcpvuresdg
+longopts=(ami-id ami-launch-index ami-manifest-path ancestor-ami-ids block-device-mapping
+          instance-id instance-type local-hostname local-ipv4 kernel-id availability-zone
+          partition product-codes public-hostname public-ipv4 public-keys ramdisk-id
+          reservation-id security-groups user-data tags help all)
+
+oldIFS="$IFS"
+IFS=,
+TEMP=$(getopt -o $shortopts --longoptions "${longopts[*]}" -n 'ec2-metadata' -- "$@")
+if [ $? -ne 0 ]; then
+    echo 'Terminating...' >&2
+    exit 1
+fi
+IFS="$oldIFS"
+
+eval set -- "$TEMP"
+unset TEMP
+
+while true; do
+    case "$1" in
+        --help)
+            print_help ; shift
+            exit 0
+            ;;
+        --)
+            shift ; break
+            ;;
+        --?*|-?)
+            # pass most arguments to the original action processing
+            # code after setting options
+            actions+=("$1"); shift
+            ;;
+        *)
+            echo 'Unknown error: ' "[$1]" >&2
+            exit 1
+            ;;
+    esac
+done
+
 #start processing command line arguments
-while [ "$1" != "" ]; do
-	case $1 in
-	-a | --ami-id )                print_normal_metric ami-id meta-data/ami-id
-																 ;;
-	-l | --ami-launch-index )      print_normal_metric ami-launch-index meta-data/ami-launch-index
-																 ;;
-	-m | --ami-manifest-path )     print_normal_metric ami-manifest-path meta-data/ami-manifest-path
-																 ;;
-	-n | --ancestor-ami-ids )      print_normal_metric ancestor-ami-ids meta-data/ancestor-ami-ids
-																 ;;
-	-b | --block-device-mapping )  print_block-device-mapping
-																 ;;
-	-i | --instance-id )           print_normal_metric instance-id meta-data/instance-id
-																 ;;
-	-t | --instance-type )         print_normal_metric instance-type meta-data/instance-type
-																 ;;
-	-h | --local-hostname )        print_normal_metric local-hostname meta-data/local-hostname
-																 ;;
-	-o | --local-ipv4 )            print_normal_metric local-ipv4 meta-data/local-ipv4
-																 ;;
-	-k | --kernel-id )             print_normal_metric kernel-id meta-data/kernel-id
-																 ;;
-	-z | --availability-zone )     print_normal_metric placement meta-data/placement/availability-zone
-																 ;;
-	-P | --partition )             print_normal_metric partition meta-data/services/partition
-																 ;;
-	-c | --product-codes )         print_normal_metric product-codes meta-data/product-codes
-																 ;;
-	-p | --public-hostname )       print_normal_metric public-hostname meta-data/public-hostname
-																 ;;
-	-v | --public-ipv4 )           print_normal_metric public-ipv4 meta-data/public-ipv4
-																 ;;
-	-u | --public-keys )           print_public-keys
-																 ;;
-	-r | --ramdisk-id )            print_normal_metric ramdisk-id /meta-data/ramdisk-id
-																 ;;
-	-e | --reservation-id )        print_normal_metric reservation-id /meta-data/reservation-id
-																 ;;
-	-s | --security-groups )       print_normal_metric security-groups meta-data/security-groups
-																 ;;
-	-d | --user-data )             print_normal_metric user-data user-data
-																 ;;
-	-g | --tags )                  print_tags
-																 ;;
-	     --help )                  print_help
-								 exit
-																 ;;
-	--all )                        print_all
-								 exit 
-																 ;;
-	* )                            print_help
-								 exit 1
+for action in "${actions[@]}"; do
+	case "$action" in
+	    -a | --ami-id )                print_normal_metric ami-id meta-data/ami-id ;;
+	    -l | --ami-launch-index )      print_normal_metric ami-launch-index meta-data/ami-launch-index ;;
+	    -m | --ami-manifest-path )     print_normal_metric ami-manifest-path meta-data/ami-manifest-path ;;
+	    -n | --ancestor-ami-ids )      print_normal_metric ancestor-ami-ids meta-data/ancestor-ami-ids ;;
+	    -b | --block-device-mapping )  print_block-device-mapping ;;
+	    -i | --instance-id )           print_normal_metric instance-id meta-data/instance-id ;;
+	    -t | --instance-type )         print_normal_metric instance-type meta-data/instance-type ;;
+	    -h | --local-hostname )        print_normal_metric local-hostname meta-data/local-hostname ;;
+	    -o | --local-ipv4 )            print_normal_metric local-ipv4 meta-data/local-ipv4 ;;
+	    -k | --kernel-id )             print_normal_metric kernel-id meta-data/kernel-id ;;
+	    -z | --availability-zone )     print_normal_metric placement meta-data/placement/availability-zone ;;
+	    -P | --partition )             print_normal_metric partition meta-data/services/partition ;;
+	    -c | --product-codes )         print_normal_metric product-codes meta-data/product-codes ;;
+	    -p | --public-hostname )       print_normal_metric public-hostname meta-data/public-hostname ;;
+	    -v | --public-ipv4 )           print_normal_metric public-ipv4 meta-data/public-ipv4 ;;
+	    -u | --public-keys )           print_public-keys ;;
+	    -r | --ramdisk-id )            print_normal_metric ramdisk-id /meta-data/ramdisk-id ;;
+	    -e | --reservation-id )        print_normal_metric reservation-id /meta-data/reservation-id ;;
+	    -s | --security-groups )       print_normal_metric security-groups meta-data/security-groups ;;
+	    -d | --user-data )             print_normal_metric user-data user-data ;;
+	    -g | --tags )                  print_tags ;;
+	    --all )                        print_all; exit ;;
 	esac
 	shift
 done
+
+exit 0
